# Generated by Django 3.0.7 on 2020-06-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200619_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(default='noemail@noemail.noemail', max_length=254),
        ),
    ]
